# Generated by Django 2.2.12 on 2020-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
