# Generated by Django 2.2.12 on 2020-05-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_avatar_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
