# Generated by Django 2.2.12 on 2020-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200523_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='avatar',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='mana',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='avatar',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
