# Generated by Django 2.2.12 on 2020-06-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200527_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
