# Generated by Django 2.2.12 on 2020-05-17 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2),
        ),
    ]
