# Generated by Django 2.2.12 on 2020-05-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200519_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
