# Generated by Django 2.2.12 on 2020-05-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200519_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='owner_name',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
